/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the RepositoryPatchDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepositoryPatchDto{}

// RepositoryPatchDto struct for RepositoryPatchDto
type RepositoryPatchDto struct {
	// The alias of the repository owner
	Owner *string `json:"owner,omitempty"`
	Url *string `json:"url,omitempty"`
	Mainline *string `json:"mainline,omitempty"`
	// the generator used for the initial contents of this repository
	Generator *string `json:"generator,omitempty"`
	Configuration *RepositoryConfigurationPatchDto `json:"configuration,omitempty"`
	// ISO-8601 UTC date time at which this information was originally committed. When sending an update, include the original timestamp you got so we can detect concurrent updates.
	TimeStamp string `json:"timeStamp" yaml:"-"`
	// The git commit hash this information was originally committed under. When sending an update, include the original commitHash you got so we can detect concurrent updates.
	CommitHash string `json:"commitHash" yaml:"-"`
	// The jira issue to use for committing a change, or the last jira issue used.
	JiraIssue string `json:"jiraIssue" yaml:"-"`
	// A map of arbitrary string labels attached to this repository.
	Labels map[string]string `json:"labels,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RepositoryPatchDto RepositoryPatchDto

// NewRepositoryPatchDto instantiates a new RepositoryPatchDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepositoryPatchDto(timeStamp string, commitHash string, jiraIssue string) *RepositoryPatchDto {
	this := RepositoryPatchDto{}
	this.TimeStamp = timeStamp
	this.CommitHash = commitHash
	this.JiraIssue = jiraIssue
	return &this
}

// NewRepositoryPatchDtoWithDefaults instantiates a new RepositoryPatchDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositoryPatchDtoWithDefaults() *RepositoryPatchDto {
	this := RepositoryPatchDto{}
	return &this
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *RepositoryPatchDto) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryPatchDto) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *RepositoryPatchDto) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *RepositoryPatchDto) SetOwner(v string) {
	o.Owner = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *RepositoryPatchDto) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryPatchDto) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *RepositoryPatchDto) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *RepositoryPatchDto) SetUrl(v string) {
	o.Url = &v
}

// GetMainline returns the Mainline field value if set, zero value otherwise.
func (o *RepositoryPatchDto) GetMainline() string {
	if o == nil || IsNil(o.Mainline) {
		var ret string
		return ret
	}
	return *o.Mainline
}

// GetMainlineOk returns a tuple with the Mainline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryPatchDto) GetMainlineOk() (*string, bool) {
	if o == nil || IsNil(o.Mainline) {
		return nil, false
	}
	return o.Mainline, true
}

// HasMainline returns a boolean if a field has been set.
func (o *RepositoryPatchDto) HasMainline() bool {
	if o != nil && !IsNil(o.Mainline) {
		return true
	}

	return false
}

// SetMainline gets a reference to the given string and assigns it to the Mainline field.
func (o *RepositoryPatchDto) SetMainline(v string) {
	o.Mainline = &v
}

// GetGenerator returns the Generator field value if set, zero value otherwise.
func (o *RepositoryPatchDto) GetGenerator() string {
	if o == nil || IsNil(o.Generator) {
		var ret string
		return ret
	}
	return *o.Generator
}

// GetGeneratorOk returns a tuple with the Generator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryPatchDto) GetGeneratorOk() (*string, bool) {
	if o == nil || IsNil(o.Generator) {
		return nil, false
	}
	return o.Generator, true
}

// HasGenerator returns a boolean if a field has been set.
func (o *RepositoryPatchDto) HasGenerator() bool {
	if o != nil && !IsNil(o.Generator) {
		return true
	}

	return false
}

// SetGenerator gets a reference to the given string and assigns it to the Generator field.
func (o *RepositoryPatchDto) SetGenerator(v string) {
	o.Generator = &v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *RepositoryPatchDto) GetConfiguration() RepositoryConfigurationPatchDto {
	if o == nil || IsNil(o.Configuration) {
		var ret RepositoryConfigurationPatchDto
		return ret
	}
	return *o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryPatchDto) GetConfigurationOk() (*RepositoryConfigurationPatchDto, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *RepositoryPatchDto) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given RepositoryConfigurationPatchDto and assigns it to the Configuration field.
func (o *RepositoryPatchDto) SetConfiguration(v RepositoryConfigurationPatchDto) {
	o.Configuration = &v
}

// GetTimeStamp returns the TimeStamp field value
func (o *RepositoryPatchDto) GetTimeStamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TimeStamp
}

// GetTimeStampOk returns a tuple with the TimeStamp field value
// and a boolean to check if the value has been set.
func (o *RepositoryPatchDto) GetTimeStampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeStamp, true
}

// SetTimeStamp sets field value
func (o *RepositoryPatchDto) SetTimeStamp(v string) {
	o.TimeStamp = v
}

// GetCommitHash returns the CommitHash field value
func (o *RepositoryPatchDto) GetCommitHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommitHash
}

// GetCommitHashOk returns a tuple with the CommitHash field value
// and a boolean to check if the value has been set.
func (o *RepositoryPatchDto) GetCommitHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommitHash, true
}

// SetCommitHash sets field value
func (o *RepositoryPatchDto) SetCommitHash(v string) {
	o.CommitHash = v
}

// GetJiraIssue returns the JiraIssue field value
func (o *RepositoryPatchDto) GetJiraIssue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JiraIssue
}

// GetJiraIssueOk returns a tuple with the JiraIssue field value
// and a boolean to check if the value has been set.
func (o *RepositoryPatchDto) GetJiraIssueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JiraIssue, true
}

// SetJiraIssue sets field value
func (o *RepositoryPatchDto) SetJiraIssue(v string) {
	o.JiraIssue = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *RepositoryPatchDto) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryPatchDto) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *RepositoryPatchDto) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *RepositoryPatchDto) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o RepositoryPatchDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepositoryPatchDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Mainline) {
		toSerialize["mainline"] = o.Mainline
	}
	if !IsNil(o.Generator) {
		toSerialize["generator"] = o.Generator
	}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	toSerialize["timeStamp"] = o.TimeStamp
	toSerialize["commitHash"] = o.CommitHash
	toSerialize["jiraIssue"] = o.JiraIssue
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RepositoryPatchDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timeStamp",
		"commitHash",
		"jiraIssue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRepositoryPatchDto := _RepositoryPatchDto{}

	err = json.Unmarshal(data, &varRepositoryPatchDto)

	if err != nil {
		return err
	}

	*o = RepositoryPatchDto(varRepositoryPatchDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "owner")
		delete(additionalProperties, "url")
		delete(additionalProperties, "mainline")
		delete(additionalProperties, "generator")
		delete(additionalProperties, "configuration")
		delete(additionalProperties, "timeStamp")
		delete(additionalProperties, "commitHash")
		delete(additionalProperties, "jiraIssue")
		delete(additionalProperties, "labels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRepositoryPatchDto struct {
	value *RepositoryPatchDto
	isSet bool
}

func (v NullableRepositoryPatchDto) Get() *RepositoryPatchDto {
	return v.value
}

func (v *NullableRepositoryPatchDto) Set(val *RepositoryPatchDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRepositoryPatchDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRepositoryPatchDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepositoryPatchDto(val *RepositoryPatchDto) *NullableRepositoryPatchDto {
	return &NullableRepositoryPatchDto{value: val, isSet: true}
}

func (v NullableRepositoryPatchDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepositoryPatchDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


