/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the RepositoryConfigurationDefaultTaskDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepositoryConfigurationDefaultTaskDto{}

// RepositoryConfigurationDefaultTaskDto struct for RepositoryConfigurationDefaultTaskDto
type RepositoryConfigurationDefaultTaskDto struct {
	Text string `json:"text"`
	AdditionalProperties map[string]interface{}
}

type _RepositoryConfigurationDefaultTaskDto RepositoryConfigurationDefaultTaskDto

// NewRepositoryConfigurationDefaultTaskDto instantiates a new RepositoryConfigurationDefaultTaskDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepositoryConfigurationDefaultTaskDto(text string) *RepositoryConfigurationDefaultTaskDto {
	this := RepositoryConfigurationDefaultTaskDto{}
	this.Text = text
	return &this
}

// NewRepositoryConfigurationDefaultTaskDtoWithDefaults instantiates a new RepositoryConfigurationDefaultTaskDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositoryConfigurationDefaultTaskDtoWithDefaults() *RepositoryConfigurationDefaultTaskDto {
	this := RepositoryConfigurationDefaultTaskDto{}
	return &this
}

// GetText returns the Text field value
func (o *RepositoryConfigurationDefaultTaskDto) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *RepositoryConfigurationDefaultTaskDto) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *RepositoryConfigurationDefaultTaskDto) SetText(v string) {
	o.Text = v
}

func (o RepositoryConfigurationDefaultTaskDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepositoryConfigurationDefaultTaskDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RepositoryConfigurationDefaultTaskDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRepositoryConfigurationDefaultTaskDto := _RepositoryConfigurationDefaultTaskDto{}

	err = json.Unmarshal(data, &varRepositoryConfigurationDefaultTaskDto)

	if err != nil {
		return err
	}

	*o = RepositoryConfigurationDefaultTaskDto(varRepositoryConfigurationDefaultTaskDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "text")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRepositoryConfigurationDefaultTaskDto struct {
	value *RepositoryConfigurationDefaultTaskDto
	isSet bool
}

func (v NullableRepositoryConfigurationDefaultTaskDto) Get() *RepositoryConfigurationDefaultTaskDto {
	return v.value
}

func (v *NullableRepositoryConfigurationDefaultTaskDto) Set(val *RepositoryConfigurationDefaultTaskDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRepositoryConfigurationDefaultTaskDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRepositoryConfigurationDefaultTaskDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepositoryConfigurationDefaultTaskDto(val *RepositoryConfigurationDefaultTaskDto) *NullableRepositoryConfigurationDefaultTaskDto {
	return &NullableRepositoryConfigurationDefaultTaskDto{value: val, isSet: true}
}

func (v NullableRepositoryConfigurationDefaultTaskDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepositoryConfigurationDefaultTaskDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


