/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the OwnerPatchDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OwnerPatchDto{}

// OwnerPatchDto struct for OwnerPatchDto
type OwnerPatchDto struct {
	// The contact information of the owner
	Contact *string `json:"contact,omitempty"`
	// The teams channel url information of the owner
	TeamsChannelURL *string `json:"teamsChannelURL,omitempty"`
	// The product owner of this owner space
	ProductOwner *string `json:"productOwner,omitempty"`
	// A list of users which constitute this owner
	Members []string `json:"members,omitempty"`
	// Map of string (group name e.g. some-owner) of strings (list of usernames), one username for each group is required.
	Groups map[string][]string `json:"groups,omitempty"`
	// A list of users that are allowed to promote services in this owner space
	Promoters []string `json:"promoters,omitempty"`
	// The default jira project that is used by this owner space
	DefaultJiraProject *string `json:"defaultJiraProject,omitempty"`
	// ISO-8601 UTC date time at which this information was originally committed. When sending an update, include the original timestamp you got so we can detect concurrent updates.
	TimeStamp string `json:"timeStamp"`
	// The git commit hash this information was originally committed under. When sending an update, include the original commitHash you got so we can detect concurrent updates.
	CommitHash string `json:"commitHash"`
	// The jira issue to use for committing a change, or the last jira issue used.
	JiraIssue string `json:"jiraIssue"`
	// A display name of the owner, to be presented in user interfaces instead of the owner's name, when available
	DisplayName *string `json:"displayName,omitempty"`
	Links []Link `json:"links,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OwnerPatchDto OwnerPatchDto

// NewOwnerPatchDto instantiates a new OwnerPatchDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOwnerPatchDto(timeStamp string, commitHash string, jiraIssue string) *OwnerPatchDto {
	this := OwnerPatchDto{}
	this.TimeStamp = timeStamp
	this.CommitHash = commitHash
	this.JiraIssue = jiraIssue
	return &this
}

// NewOwnerPatchDtoWithDefaults instantiates a new OwnerPatchDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOwnerPatchDtoWithDefaults() *OwnerPatchDto {
	this := OwnerPatchDto{}
	return &this
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *OwnerPatchDto) GetContact() string {
	if o == nil || IsNil(o.Contact) {
		var ret string
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerPatchDto) GetContactOk() (*string, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *OwnerPatchDto) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given string and assigns it to the Contact field.
func (o *OwnerPatchDto) SetContact(v string) {
	o.Contact = &v
}

// GetTeamsChannelURL returns the TeamsChannelURL field value if set, zero value otherwise.
func (o *OwnerPatchDto) GetTeamsChannelURL() string {
	if o == nil || IsNil(o.TeamsChannelURL) {
		var ret string
		return ret
	}
	return *o.TeamsChannelURL
}

// GetTeamsChannelURLOk returns a tuple with the TeamsChannelURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerPatchDto) GetTeamsChannelURLOk() (*string, bool) {
	if o == nil || IsNil(o.TeamsChannelURL) {
		return nil, false
	}
	return o.TeamsChannelURL, true
}

// HasTeamsChannelURL returns a boolean if a field has been set.
func (o *OwnerPatchDto) HasTeamsChannelURL() bool {
	if o != nil && !IsNil(o.TeamsChannelURL) {
		return true
	}

	return false
}

// SetTeamsChannelURL gets a reference to the given string and assigns it to the TeamsChannelURL field.
func (o *OwnerPatchDto) SetTeamsChannelURL(v string) {
	o.TeamsChannelURL = &v
}

// GetProductOwner returns the ProductOwner field value if set, zero value otherwise.
func (o *OwnerPatchDto) GetProductOwner() string {
	if o == nil || IsNil(o.ProductOwner) {
		var ret string
		return ret
	}
	return *o.ProductOwner
}

// GetProductOwnerOk returns a tuple with the ProductOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerPatchDto) GetProductOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.ProductOwner) {
		return nil, false
	}
	return o.ProductOwner, true
}

// HasProductOwner returns a boolean if a field has been set.
func (o *OwnerPatchDto) HasProductOwner() bool {
	if o != nil && !IsNil(o.ProductOwner) {
		return true
	}

	return false
}

// SetProductOwner gets a reference to the given string and assigns it to the ProductOwner field.
func (o *OwnerPatchDto) SetProductOwner(v string) {
	o.ProductOwner = &v
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *OwnerPatchDto) GetMembers() []string {
	if o == nil || IsNil(o.Members) {
		var ret []string
		return ret
	}
	return o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerPatchDto) GetMembersOk() ([]string, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *OwnerPatchDto) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given []string and assigns it to the Members field.
func (o *OwnerPatchDto) SetMembers(v []string) {
	o.Members = v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *OwnerPatchDto) GetGroups() map[string][]string {
	if o == nil || IsNil(o.Groups) {
		var ret map[string][]string
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerPatchDto) GetGroupsOk() (map[string][]string, bool) {
	if o == nil || IsNil(o.Groups) {
		return map[string][]string{}, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *OwnerPatchDto) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given map[string][]string and assigns it to the Groups field.
func (o *OwnerPatchDto) SetGroups(v map[string][]string) {
	o.Groups = v
}

// GetPromoters returns the Promoters field value if set, zero value otherwise.
func (o *OwnerPatchDto) GetPromoters() []string {
	if o == nil || IsNil(o.Promoters) {
		var ret []string
		return ret
	}
	return o.Promoters
}

// GetPromotersOk returns a tuple with the Promoters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerPatchDto) GetPromotersOk() ([]string, bool) {
	if o == nil || IsNil(o.Promoters) {
		return nil, false
	}
	return o.Promoters, true
}

// HasPromoters returns a boolean if a field has been set.
func (o *OwnerPatchDto) HasPromoters() bool {
	if o != nil && !IsNil(o.Promoters) {
		return true
	}

	return false
}

// SetPromoters gets a reference to the given []string and assigns it to the Promoters field.
func (o *OwnerPatchDto) SetPromoters(v []string) {
	o.Promoters = v
}

// GetDefaultJiraProject returns the DefaultJiraProject field value if set, zero value otherwise.
func (o *OwnerPatchDto) GetDefaultJiraProject() string {
	if o == nil || IsNil(o.DefaultJiraProject) {
		var ret string
		return ret
	}
	return *o.DefaultJiraProject
}

// GetDefaultJiraProjectOk returns a tuple with the DefaultJiraProject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerPatchDto) GetDefaultJiraProjectOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultJiraProject) {
		return nil, false
	}
	return o.DefaultJiraProject, true
}

// HasDefaultJiraProject returns a boolean if a field has been set.
func (o *OwnerPatchDto) HasDefaultJiraProject() bool {
	if o != nil && !IsNil(o.DefaultJiraProject) {
		return true
	}

	return false
}

// SetDefaultJiraProject gets a reference to the given string and assigns it to the DefaultJiraProject field.
func (o *OwnerPatchDto) SetDefaultJiraProject(v string) {
	o.DefaultJiraProject = &v
}

// GetTimeStamp returns the TimeStamp field value
func (o *OwnerPatchDto) GetTimeStamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TimeStamp
}

// GetTimeStampOk returns a tuple with the TimeStamp field value
// and a boolean to check if the value has been set.
func (o *OwnerPatchDto) GetTimeStampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeStamp, true
}

// SetTimeStamp sets field value
func (o *OwnerPatchDto) SetTimeStamp(v string) {
	o.TimeStamp = v
}

// GetCommitHash returns the CommitHash field value
func (o *OwnerPatchDto) GetCommitHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommitHash
}

// GetCommitHashOk returns a tuple with the CommitHash field value
// and a boolean to check if the value has been set.
func (o *OwnerPatchDto) GetCommitHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommitHash, true
}

// SetCommitHash sets field value
func (o *OwnerPatchDto) SetCommitHash(v string) {
	o.CommitHash = v
}

// GetJiraIssue returns the JiraIssue field value
func (o *OwnerPatchDto) GetJiraIssue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JiraIssue
}

// GetJiraIssueOk returns a tuple with the JiraIssue field value
// and a boolean to check if the value has been set.
func (o *OwnerPatchDto) GetJiraIssueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JiraIssue, true
}

// SetJiraIssue sets field value
func (o *OwnerPatchDto) SetJiraIssue(v string) {
	o.JiraIssue = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *OwnerPatchDto) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerPatchDto) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *OwnerPatchDto) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *OwnerPatchDto) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *OwnerPatchDto) GetLinks() []Link {
	if o == nil || IsNil(o.Links) {
		var ret []Link
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerPatchDto) GetLinksOk() ([]Link, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *OwnerPatchDto) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []Link and assigns it to the Links field.
func (o *OwnerPatchDto) SetLinks(v []Link) {
	o.Links = v
}

func (o OwnerPatchDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OwnerPatchDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	if !IsNil(o.TeamsChannelURL) {
		toSerialize["teamsChannelURL"] = o.TeamsChannelURL
	}
	if !IsNil(o.ProductOwner) {
		toSerialize["productOwner"] = o.ProductOwner
	}
	if !IsNil(o.Members) {
		toSerialize["members"] = o.Members
	}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	if !IsNil(o.Promoters) {
		toSerialize["promoters"] = o.Promoters
	}
	if !IsNil(o.DefaultJiraProject) {
		toSerialize["defaultJiraProject"] = o.DefaultJiraProject
	}
	toSerialize["timeStamp"] = o.TimeStamp
	toSerialize["commitHash"] = o.CommitHash
	toSerialize["jiraIssue"] = o.JiraIssue
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OwnerPatchDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timeStamp",
		"commitHash",
		"jiraIssue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOwnerPatchDto := _OwnerPatchDto{}

	err = json.Unmarshal(data, &varOwnerPatchDto)

	if err != nil {
		return err
	}

	*o = OwnerPatchDto(varOwnerPatchDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "contact")
		delete(additionalProperties, "teamsChannelURL")
		delete(additionalProperties, "productOwner")
		delete(additionalProperties, "members")
		delete(additionalProperties, "groups")
		delete(additionalProperties, "promoters")
		delete(additionalProperties, "defaultJiraProject")
		delete(additionalProperties, "timeStamp")
		delete(additionalProperties, "commitHash")
		delete(additionalProperties, "jiraIssue")
		delete(additionalProperties, "displayName")
		delete(additionalProperties, "links")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOwnerPatchDto struct {
	value *OwnerPatchDto
	isSet bool
}

func (v NullableOwnerPatchDto) Get() *OwnerPatchDto {
	return v.value
}

func (v *NullableOwnerPatchDto) Set(val *OwnerPatchDto) {
	v.value = val
	v.isSet = true
}

func (v NullableOwnerPatchDto) IsSet() bool {
	return v.isSet
}

func (v *NullableOwnerPatchDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOwnerPatchDto(val *OwnerPatchDto) *NullableOwnerPatchDto {
	return &NullableOwnerPatchDto{value: val, isSet: true}
}

func (v NullableOwnerPatchDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOwnerPatchDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


