/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the DeletionDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletionDto{}

// DeletionDto struct for DeletionDto
type DeletionDto struct {
	// The jira issue to use for committing the deletion.
	JiraIssue string `json:"jiraIssue"`
	AdditionalProperties map[string]interface{}
}

type _DeletionDto DeletionDto

// NewDeletionDto instantiates a new DeletionDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletionDto(jiraIssue string) *DeletionDto {
	this := DeletionDto{}
	this.JiraIssue = jiraIssue
	return &this
}

// NewDeletionDtoWithDefaults instantiates a new DeletionDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletionDtoWithDefaults() *DeletionDto {
	this := DeletionDto{}
	return &this
}

// GetJiraIssue returns the JiraIssue field value
func (o *DeletionDto) GetJiraIssue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JiraIssue
}

// GetJiraIssueOk returns a tuple with the JiraIssue field value
// and a boolean to check if the value has been set.
func (o *DeletionDto) GetJiraIssueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JiraIssue, true
}

// SetJiraIssue sets field value
func (o *DeletionDto) SetJiraIssue(v string) {
	o.JiraIssue = v
}

func (o DeletionDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletionDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jiraIssue"] = o.JiraIssue

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeletionDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jiraIssue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeletionDto := _DeletionDto{}

	err = json.Unmarshal(data, &varDeletionDto)

	if err != nil {
		return err
	}

	*o = DeletionDto(varDeletionDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "jiraIssue")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeletionDto struct {
	value *DeletionDto
	isSet bool
}

func (v NullableDeletionDto) Get() *DeletionDto {
	return v.value
}

func (v *NullableDeletionDto) Set(val *DeletionDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletionDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletionDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletionDto(val *DeletionDto) *NullableDeletionDto {
	return &NullableDeletionDto{value: val, isSet: true}
}

func (v NullableDeletionDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletionDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


