/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ServiceListDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceListDto{}

// ServiceListDto struct for ServiceListDto
type ServiceListDto struct {
	Services map[string]ServiceDto `json:"services"`
	// ISO-8601 UTC date time at which the list of services was obtained from service-metadata
	TimeStamp string `json:"timeStamp"`
	AdditionalProperties map[string]interface{}
}

type _ServiceListDto ServiceListDto

// NewServiceListDto instantiates a new ServiceListDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceListDto(services map[string]ServiceDto, timeStamp string) *ServiceListDto {
	this := ServiceListDto{}
	this.Services = services
	this.TimeStamp = timeStamp
	return &this
}

// NewServiceListDtoWithDefaults instantiates a new ServiceListDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceListDtoWithDefaults() *ServiceListDto {
	this := ServiceListDto{}
	return &this
}

// GetServices returns the Services field value
func (o *ServiceListDto) GetServices() map[string]ServiceDto {
	if o == nil {
		var ret map[string]ServiceDto
		return ret
	}

	return o.Services
}

// GetServicesOk returns a tuple with the Services field value
// and a boolean to check if the value has been set.
func (o *ServiceListDto) GetServicesOk() (map[string]ServiceDto, bool) {
	if o == nil {
		return map[string]ServiceDto{}, false
	}
	return o.Services, true
}

// SetServices sets field value
func (o *ServiceListDto) SetServices(v map[string]ServiceDto) {
	o.Services = v
}

// GetTimeStamp returns the TimeStamp field value
func (o *ServiceListDto) GetTimeStamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TimeStamp
}

// GetTimeStampOk returns a tuple with the TimeStamp field value
// and a boolean to check if the value has been set.
func (o *ServiceListDto) GetTimeStampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeStamp, true
}

// SetTimeStamp sets field value
func (o *ServiceListDto) SetTimeStamp(v string) {
	o.TimeStamp = v
}

func (o ServiceListDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceListDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["services"] = o.Services
	toSerialize["timeStamp"] = o.TimeStamp

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceListDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"services",
		"timeStamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceListDto := _ServiceListDto{}

	err = json.Unmarshal(data, &varServiceListDto)

	if err != nil {
		return err
	}

	*o = ServiceListDto(varServiceListDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "services")
		delete(additionalProperties, "timeStamp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceListDto struct {
	value *ServiceListDto
	isSet bool
}

func (v NullableServiceListDto) Get() *ServiceListDto {
	return v.value
}

func (v *NullableServiceListDto) Set(val *ServiceListDto) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceListDto) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceListDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceListDto(val *ServiceListDto) *NullableServiceListDto {
	return &NullableServiceListDto{value: val, isSet: true}
}

func (v NullableServiceListDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceListDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


