/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RefProtectionsBranches type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefProtectionsBranches{}

// RefProtectionsBranches struct for RefProtectionsBranches
type RefProtectionsBranches struct {
	// Forces creating a PR to update the protected refs.
	RequirePR []ProtectedRef `json:"requirePR,omitempty"`
	// Prevents all changes of the protected refs.
	PreventAllChanges []ProtectedRef `json:"preventAllChanges,omitempty"`
	// Prevents creation of the protected refs.
	PreventCreation []ProtectedRef `json:"preventCreation,omitempty"`
	// Prevents deletion of the protected refs.
	PreventDeletion []ProtectedRef `json:"preventDeletion,omitempty"`
	// Prevents pushes to the protected refs.
	PreventPush []ProtectedRef `json:"preventPush,omitempty"`
	// Prevents force pushes to the protected refs for users with push permission.
	PreventForcePush []ProtectedRef `json:"preventForcePush,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RefProtectionsBranches RefProtectionsBranches

// NewRefProtectionsBranches instantiates a new RefProtectionsBranches object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefProtectionsBranches() *RefProtectionsBranches {
	this := RefProtectionsBranches{}
	return &this
}

// NewRefProtectionsBranchesWithDefaults instantiates a new RefProtectionsBranches object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefProtectionsBranchesWithDefaults() *RefProtectionsBranches {
	this := RefProtectionsBranches{}
	return &this
}

// GetRequirePR returns the RequirePR field value if set, zero value otherwise.
func (o *RefProtectionsBranches) GetRequirePR() []ProtectedRef {
	if o == nil || IsNil(o.RequirePR) {
		var ret []ProtectedRef
		return ret
	}
	return o.RequirePR
}

// GetRequirePROk returns a tuple with the RequirePR field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefProtectionsBranches) GetRequirePROk() ([]ProtectedRef, bool) {
	if o == nil || IsNil(o.RequirePR) {
		return nil, false
	}
	return o.RequirePR, true
}

// HasRequirePR returns a boolean if a field has been set.
func (o *RefProtectionsBranches) HasRequirePR() bool {
	if o != nil && !IsNil(o.RequirePR) {
		return true
	}

	return false
}

// SetRequirePR gets a reference to the given []ProtectedRef and assigns it to the RequirePR field.
func (o *RefProtectionsBranches) SetRequirePR(v []ProtectedRef) {
	o.RequirePR = v
}

// GetPreventAllChanges returns the PreventAllChanges field value if set, zero value otherwise.
func (o *RefProtectionsBranches) GetPreventAllChanges() []ProtectedRef {
	if o == nil || IsNil(o.PreventAllChanges) {
		var ret []ProtectedRef
		return ret
	}
	return o.PreventAllChanges
}

// GetPreventAllChangesOk returns a tuple with the PreventAllChanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefProtectionsBranches) GetPreventAllChangesOk() ([]ProtectedRef, bool) {
	if o == nil || IsNil(o.PreventAllChanges) {
		return nil, false
	}
	return o.PreventAllChanges, true
}

// HasPreventAllChanges returns a boolean if a field has been set.
func (o *RefProtectionsBranches) HasPreventAllChanges() bool {
	if o != nil && !IsNil(o.PreventAllChanges) {
		return true
	}

	return false
}

// SetPreventAllChanges gets a reference to the given []ProtectedRef and assigns it to the PreventAllChanges field.
func (o *RefProtectionsBranches) SetPreventAllChanges(v []ProtectedRef) {
	o.PreventAllChanges = v
}

// GetPreventCreation returns the PreventCreation field value if set, zero value otherwise.
func (o *RefProtectionsBranches) GetPreventCreation() []ProtectedRef {
	if o == nil || IsNil(o.PreventCreation) {
		var ret []ProtectedRef
		return ret
	}
	return o.PreventCreation
}

// GetPreventCreationOk returns a tuple with the PreventCreation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefProtectionsBranches) GetPreventCreationOk() ([]ProtectedRef, bool) {
	if o == nil || IsNil(o.PreventCreation) {
		return nil, false
	}
	return o.PreventCreation, true
}

// HasPreventCreation returns a boolean if a field has been set.
func (o *RefProtectionsBranches) HasPreventCreation() bool {
	if o != nil && !IsNil(o.PreventCreation) {
		return true
	}

	return false
}

// SetPreventCreation gets a reference to the given []ProtectedRef and assigns it to the PreventCreation field.
func (o *RefProtectionsBranches) SetPreventCreation(v []ProtectedRef) {
	o.PreventCreation = v
}

// GetPreventDeletion returns the PreventDeletion field value if set, zero value otherwise.
func (o *RefProtectionsBranches) GetPreventDeletion() []ProtectedRef {
	if o == nil || IsNil(o.PreventDeletion) {
		var ret []ProtectedRef
		return ret
	}
	return o.PreventDeletion
}

// GetPreventDeletionOk returns a tuple with the PreventDeletion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefProtectionsBranches) GetPreventDeletionOk() ([]ProtectedRef, bool) {
	if o == nil || IsNil(o.PreventDeletion) {
		return nil, false
	}
	return o.PreventDeletion, true
}

// HasPreventDeletion returns a boolean if a field has been set.
func (o *RefProtectionsBranches) HasPreventDeletion() bool {
	if o != nil && !IsNil(o.PreventDeletion) {
		return true
	}

	return false
}

// SetPreventDeletion gets a reference to the given []ProtectedRef and assigns it to the PreventDeletion field.
func (o *RefProtectionsBranches) SetPreventDeletion(v []ProtectedRef) {
	o.PreventDeletion = v
}

// GetPreventPush returns the PreventPush field value if set, zero value otherwise.
func (o *RefProtectionsBranches) GetPreventPush() []ProtectedRef {
	if o == nil || IsNil(o.PreventPush) {
		var ret []ProtectedRef
		return ret
	}
	return o.PreventPush
}

// GetPreventPushOk returns a tuple with the PreventPush field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefProtectionsBranches) GetPreventPushOk() ([]ProtectedRef, bool) {
	if o == nil || IsNil(o.PreventPush) {
		return nil, false
	}
	return o.PreventPush, true
}

// HasPreventPush returns a boolean if a field has been set.
func (o *RefProtectionsBranches) HasPreventPush() bool {
	if o != nil && !IsNil(o.PreventPush) {
		return true
	}

	return false
}

// SetPreventPush gets a reference to the given []ProtectedRef and assigns it to the PreventPush field.
func (o *RefProtectionsBranches) SetPreventPush(v []ProtectedRef) {
	o.PreventPush = v
}

// GetPreventForcePush returns the PreventForcePush field value if set, zero value otherwise.
func (o *RefProtectionsBranches) GetPreventForcePush() []ProtectedRef {
	if o == nil || IsNil(o.PreventForcePush) {
		var ret []ProtectedRef
		return ret
	}
	return o.PreventForcePush
}

// GetPreventForcePushOk returns a tuple with the PreventForcePush field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefProtectionsBranches) GetPreventForcePushOk() ([]ProtectedRef, bool) {
	if o == nil || IsNil(o.PreventForcePush) {
		return nil, false
	}
	return o.PreventForcePush, true
}

// HasPreventForcePush returns a boolean if a field has been set.
func (o *RefProtectionsBranches) HasPreventForcePush() bool {
	if o != nil && !IsNil(o.PreventForcePush) {
		return true
	}

	return false
}

// SetPreventForcePush gets a reference to the given []ProtectedRef and assigns it to the PreventForcePush field.
func (o *RefProtectionsBranches) SetPreventForcePush(v []ProtectedRef) {
	o.PreventForcePush = v
}

func (o RefProtectionsBranches) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefProtectionsBranches) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequirePR) {
		toSerialize["requirePR"] = o.RequirePR
	}
	if !IsNil(o.PreventAllChanges) {
		toSerialize["preventAllChanges"] = o.PreventAllChanges
	}
	if !IsNil(o.PreventCreation) {
		toSerialize["preventCreation"] = o.PreventCreation
	}
	if !IsNil(o.PreventDeletion) {
		toSerialize["preventDeletion"] = o.PreventDeletion
	}
	if !IsNil(o.PreventPush) {
		toSerialize["preventPush"] = o.PreventPush
	}
	if !IsNil(o.PreventForcePush) {
		toSerialize["preventForcePush"] = o.PreventForcePush
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RefProtectionsBranches) UnmarshalJSON(data []byte) (err error) {
	varRefProtectionsBranches := _RefProtectionsBranches{}

	err = json.Unmarshal(data, &varRefProtectionsBranches)

	if err != nil {
		return err
	}

	*o = RefProtectionsBranches(varRefProtectionsBranches)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requirePR")
		delete(additionalProperties, "preventAllChanges")
		delete(additionalProperties, "preventCreation")
		delete(additionalProperties, "preventDeletion")
		delete(additionalProperties, "preventPush")
		delete(additionalProperties, "preventForcePush")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRefProtectionsBranches struct {
	value *RefProtectionsBranches
	isSet bool
}

func (v NullableRefProtectionsBranches) Get() *RefProtectionsBranches {
	return v.value
}

func (v *NullableRefProtectionsBranches) Set(val *RefProtectionsBranches) {
	v.value = val
	v.isSet = true
}

func (v NullableRefProtectionsBranches) IsSet() bool {
	return v.isSet
}

func (v *NullableRefProtectionsBranches) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefProtectionsBranches(val *RefProtectionsBranches) *NullableRefProtectionsBranches {
	return &NullableRefProtectionsBranches{value: val, isSet: true}
}

func (v NullableRefProtectionsBranches) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefProtectionsBranches) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


