name: API

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  generate:
    name: 🛠️ Generate
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: pnpm generate:api
      - name: Check for API spec changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "API spec is outdated. Please run 'npm run generate:api' locally and commit the changes."
            exit 1
          fi

  release:
    name: 🚀 Release
    if: github.ref == 'refs/heads/main'
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: semantic-release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          allow-initial-development-versions: true # remove to trigger an initial 1.0.0 release
          changelog-generator-opt: "emojis=true"
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: repository-id
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      - if: steps.semantic-release.outputs.version != ''
        run: |
          TARGET=ghcr.io/${{ steps.repository-id.outputs.lowercase }}:${{ steps.semantic-release.outputs.version }}
          SOURCE=${{ needs.build.outputs.image }}

          docker pull $SOURCE
          docker tag $SOURCE $TARGET
          docker push $TARGET
